title = "Car Setup"

[carparams]
max_forward_speed  = 20.0
max_backward_speed = -10.0
max_lateral_impulse = 10.5
steer_torque = 0.01
steer_torque_offset = 0.004
max_drive_force = 5.0
angular_damping = 0.3
angular_friction = 0.023
body_density  = 0.1
traction = 0.1
drift_friction = 0.5
drag_modifier = 0.01
steer_allow_speed = 0.1

[carbody]
body_vertices = [[0.15, 0.0],
                [0.3, 0.25],
                [0.28, 0.55],
                [0.10, 1.0],
                [-0.1, 1.0],
                [-0.28, 0.55],
                [-0.30, 0.25],
                [-0.1, 0.0]]

joints = [

          { local_anchorA = [-0.3, 0.0],local_anchorB=[0.0, 0.0], frontleft=true},
           { local_anchorA = [ 0.3, 0.0],local_anchorB=[0.0, 0.0], frontright=true}]

[sensors]
sensors =[{type="RAYCAST", angle=90.0 ,  enabled=0, weight=1.0 },
          {type="RAYCAST", angle=45.0 ,  enabled=1, weight=1.0 },
          {type="RAYCAST", angle=-45.0 , enabled=1, weight=1.0 },
          {type="RAYCAST", angle=-90.0 , enabled=0, weight=1.0 },
          {type="RAYCAST", angle=0.0 ,   enabled=0, weight=1.0 },
          {type="VELOCITY" ,             enabled=0, weight=1.0 },
          {type="LEFTDISTANCE" ,         enabled=0, weight=1.0 },
          {type="TRACKANGLE" ,           enabled=0, weight=1.0 },
          {type="DISTANCETOCENTERLINE" , enabled=0, weight=1.0 }]
