title = "Car Setup"

[carparams]
max_forward_speed  = 61.0
max_backward_speed = -40.0
back_tire_max_drive_force = 100.0
front_tire_max_drive_force = 150.0
back_tire_max_lateral_impulse = 8.5
front_tire_max_lateral_impulse = 7.5
angular_damping = 3.0
body_density  = 0.1

[carbody]
body_vertices = [[1.5, 0.0],
                [3.0, 2.5],
                [2.8, 5.5],
                [1.0, 10.0],
                [-1.0, 10.0],
                [-2.8, 5.5],
                [-3.0, 2.5],
                [-1.0, 0.0]]

joints = [ { local_anchorA = [-3.0,0.75], backleft=true},
           { local_anchorA = [ 3.0,0.75], backright=true},
           { local_anchorA = [-3.0, 8.5], frontleft=true},
           { local_anchorA = [ 3.0, 8.5], frontright=true}]
