[RaceSettings]
racers=[
  {name="Player", type="player",  color={r=0.75,g=0.192,b=0.0}},
  {name="BasicAI1", type="basic_ai",color={r=1.0,g=0.98,b=0.81},params=[1.0,10.0,0.05,5.0,0.0111]},
  {name="BasicAI2", type="basic_ai",color={r=1.0,g=0.98,b=0.61},params=[0.993,7.0,0.06757,8.0,0.0003]},

]
lap_number = 2
max_race_time = 300000
draw_raycast= true
draw_intputs= true
draw_outputs=true

[DifferentialEvolution]
max_iterations= 50
lap_number = 1000
max_race_time = 500
population_size= 100
differential_weight = 1.0
crossover_probability= 0.5
