title = "Track generation settings file"

[tracksettings]
track_size = 360
down_step = 30
sector_step = 5
track_width = 10
radius_curvature = [-10, 20]
radius_offset_curvature = 20
hard_curvature_probability = [0,3,5]
hard_curvature_value = 20
smooth_iterations = 400
physics_wall_size_inner = [0.05,0.05]
physics_wall_size_outer = [0.05,0.05]

color_sectors = {r=1.0,g=0.6,b=0.0}
color_wall    = {r=1.0,g=0.6,b=0.0}
